=== humeng1010/JavaSE/src/day09/data.dtd
<!ELEMENT books (book+)>
        <!ELEMENT book (bookName,author,price)>
        <!ELEMENT bookName (#PCDATA)>
        <!ELEMENT author (#PCDATA)>
        <!ELEMENT price (#PCDATA)>

=== humeng1010/JavaSE/src/day09/book.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE books SYSTEM "data.dtd">
<books>
    <book>
        <bookName>西游记</bookName>
        <author>吴承恩</author>
        <price>100</price>
    </book>
    <book>
        <bookName>西游记</bookName>
        <author>吴承恩</author>
        <price>100</price>
    </book>
    <book>
        <bookName>西游记</bookName>
        <author>吴承恩</author>
        <price>100</price>
    </book>
</books>
